services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ur_services_dev
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  ur_services:
    build:
      context: .
    depends_on:
      - database
    environment:
      DATABASE_URL: ecto://postgres:postgres@database/ur_services_dev
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${HOST}
    ports:
      - 4000:4000
    restart: unless-stopped
    profiles:
      - app

volumes:
  postgres:
  uploads:
